### ISSUE TITLE
Login Screen - White input text color on white input background

### ISSUE THREAD

**Issue by DiglidiDudeNG** [rosivanov/npmjs-dark-theme#2]
http://prntscr.com/ag3eki

As you can see, the input text is unreadable on the login screen.
Either remove them from the selector that applies the `color: white` property or change the background of `input:text` elements.

**Comment by rosivanov** [comment]
Hi Felix, thank you for mention this problem and sorry for late reply. I've fixed it. Please update styles via stylish settings.
