### ISSUE TITLE
Text in code-blocks partially unreadable

### ISSUE THREAD

**Issue by Fusl** [rosivanov/npmjs-dark-theme#6]
Hi,

first of all, thank you very much for providing the community with such a great theme, I really appreciate it as it doesn't make my eyes hurt when coding in the night :)

Something seems to have happened recently as I am having a hard time trying to read some of the syntax-highlighted text in code blocks, for example:

![1487134607085683744](https://cloud.githubusercontent.com/assets/2349496/22961118/dc52ab10-f343-11e6-9a6e-3a6e7332a22a.png)
URL from where I have taken the screenshot: https://www.npmjs.com/package/launchpad-mini#usage

Is it possible that you can provide a fix for this by either changing the background color or the syntax highlight color?

Thanks

**Comment by rosivanov** [comment]
@Fusl Hi thank you for describing this problem! I've fixed it, you can update styles. If you find more mistakes please let me know!
