### ISSUE TITLE
Text miscolored in code blocks

### ISSUE THREAD

**Issue by luop90** [rosivanov/npmjs-dark-theme#7]
Certain text in code blocks is virtually impossible to see.

Example: https://www.npmjs.com/package/steamid

**Comment by rosivanov** [comment]
Hi, are you talking about this block? http://joxi.ru/LmG7oZqIeZP59m

**Comment by rosivanov** [comment]
Hi, code blocks look good http://joxi.ru/xAe8WPNupVGaw2
Can you pls make scrshot? or maybe try to update styles?

**Comment by luop90** [comment]
The style needed to be updated. 

All good now.

**Comment by rosivanov** [comment]
:+1:
