### ISSUE TITLE
Text in code-blocks partially unreadable

### ISSUE THREAD

**Issue by Fusl** [rosivanov/npmjs-dark-theme#8]
Hi,

similar to #6, text in code blocks are again mostly unreadable. Mind taking a look?

![](https://de-fks-1.rgw.li/xor.meo.ws/f3875dbb/ac2f/42c8/8cb8/a7d4a85a9d17.png)

[Example NPM site](https://www.npmjs.com/package/iptoasn)

Thanks

**Comment by rosivanov** [comment]
@Fusl Thanks for the info! Npm has released new ui and obviously the whole theme needs for update. Will try to update asap.

**Comment by rosivanov** [comment]
relates to #9
