### ISSUE TITLE
Theme out of date

### ISSUE THREAD

**Issue by sploders101** [rosivanov/npmjs-dark-theme#9]
I would really enjoy using this theme, but unfortunately, npm recently redesigned their website, rendering this theme unusable. If you wouldn't mind updating it, that would be awesome. Thanks!

**Comment by rosivanov** [comment]
@sploders101 Thanks for the info! Obviously the whole theme needs for update. Will try to update asap.

**Comment by strugee** [comment]
@rosivanov I plan to work on this a bit. Not sure if I'll get the whole thing done but I can at least PR you some incremental improvements :thumbsup:

**Comment by rosivanov** [comment]
@strugee Thanks in advance! :relaxed: Sure I'll add your PR.
unfortunately have not enought time right now, hope will be more free close to weekends

**Comment by rosivanov** [comment]
Hi all! I've updated the theme, see http://dl3.joxi.net/drive/2018/04/02/0008/1563/570907/07/48ef5a7a5e.png
Right now it is avaliable for package page only.
I'm sure there can be some bugs with code highlight so you can creat issues or PR with fix.

@Fusl @sploders101 @strugee
